Attempt to fix UnicodeEncodeError caused by bad characters in mail message
That is, errors of the kind:
UnicodeEncodeError: 'gb2312' codec can't encode character '\ufffd' in
position 428: illegal multibyte sequence